# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screwdriver_Detection_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screwdriver_Detection_Window(object):
    def setupUi(self, Screwdriver_Detection_Window):
        Screwdriver_Detection_Window.setObjectName("Screwdriver_Detection_Window")
        Screwdriver_Detection_Window.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Screwdriver_Detection_Window.sizePolicy().hasHeightForWidth())
        Screwdriver_Detection_Window.setSizePolicy(sizePolicy)
        Screwdriver_Detection_Window.setMinimumSize(QtCore.QSize(1920, 1080))
        Screwdriver_Detection_Window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Logo/Lancer Small Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Screwdriver_Detection_Window.setWindowIcon(icon)
        Screwdriver_Detection_Window.setStyleSheet("background: \'white\';")
        self.centralwidget = QtWidgets.QWidget(Screwdriver_Detection_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image.sizePolicy().hasHeightForWidth())
        self.label_Image.setSizePolicy(sizePolicy)
        self.label_Image.setMinimumSize(QtCore.QSize(500, 919))
        self.label_Image.setStyleSheet("box-shadow: 0px 0px 16px 20px rgba(0,0,0,1);")
        self.label_Image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout_3.addWidget(self.label_Image)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_OK = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_OK.sizePolicy().hasHeightForWidth())
        self.label_OK.setSizePolicy(sizePolicy)
        self.label_OK.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.label_OK.setFont(font)
        self.label_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.label_OK.setText("")
        self.label_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OK.setObjectName("label_OK")
        self.verticalLayout_3.addWidget(self.label_OK)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Logo.sizePolicy().hasHeightForWidth())
        self.label_Logo.setSizePolicy(sizePolicy)
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap("UI_Logo/Lancer Logo_origin_629.png"))
        self.label_Logo.setScaledContents(False)
        self.label_Logo.setObjectName("label_Logo")
        self.verticalLayout.addWidget(self.label_Logo)
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start.sizePolicy().hasHeightForWidth())
        self.pushButton_Start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(60)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Start {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.verticalLayout.addWidget(self.pushButton_Start)
        spacerItem1 = QtWidgets.QSpacerItem(5, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Reset.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Reset.sizePolicy().hasHeightForWidth())
        self.pushButton_Reset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(60)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setStyleSheet("QPushButton {\n"
"    background-color: #ae4446;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #fffdfd;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #883538;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"}\n"
"\n"
"#pushButton_Reset {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.verticalLayout.addWidget(self.pushButton_Reset)
        spacerItem2 = QtWidgets.QSpacerItem(5, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_ReDetect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ReDetect.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ReDetect.sizePolicy().hasHeightForWidth())
        self.pushButton_ReDetect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(60)
        self.pushButton_ReDetect.setFont(font)
        self.pushButton_ReDetect.setStyleSheet("QPushButton {\n"
"    background-color: #e1e1e1;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"}\n"
"\n"
"#pushButton_ReDetect {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_ReDetect.setObjectName("pushButton_ReDetect")
        self.verticalLayout.addWidget(self.pushButton_ReDetect)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_Load_Recipe = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Load_Recipe.sizePolicy().hasHeightForWidth())
        self.pushButton_Load_Recipe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.pushButton_Load_Recipe.setFont(font)
        self.pushButton_Load_Recipe.setStyleSheet("QPushButton {\n"
"    color: rgb(109, 140, 145);\n"
"    background-color: #e1e1e1;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #6d8c91;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"}\n"
"\n"
"#pushButton_Load_Recipe{\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Load_Recipe.setObjectName("pushButton_Load_Recipe")
        self.verticalLayout.addWidget(self.pushButton_Load_Recipe)
        spacerItem4 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton_Recipe_End = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Recipe_End.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Recipe_End.sizePolicy().hasHeightForWidth())
        self.pushButton_Recipe_End.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.pushButton_Recipe_End.setFont(font)
        self.pushButton_Recipe_End.setStyleSheet("QPushButton {\n"
"    background-color: #e1e1e1;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #6d8c91;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"}\n"
"\n"
"#pushButton_Recipe_End{\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Recipe_End.setObjectName("pushButton_Recipe_End")
        self.verticalLayout.addWidget(self.pushButton_Recipe_End)
        spacerItem5 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.pushButton_engineer_mode = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_engineer_mode.sizePolicy().hasHeightForWidth())
        self.pushButton_engineer_mode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.pushButton_engineer_mode.setFont(font)
        self.pushButton_engineer_mode.setStyleSheet("QPushButton {\n"
"    background-color: #e1e1e1;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #6d8c91;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ecf5ff;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #3a8ee6;\n"
"}\n"
"\n"
"#pushButton_engineer_mode{\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_engineer_mode.setObjectName("pushButton_engineer_mode")
        self.verticalLayout.addWidget(self.pushButton_engineer_mode)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(5, 2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_workNumber = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_workNumber.setFont(font)
        self.label_workNumber.setStyleSheet("")
        self.label_workNumber.setObjectName("label_workNumber")
        self.verticalLayout_2.addWidget(self.label_workNumber)
        self.label_ForRecipe_Change = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_ForRecipe_Change.setFont(font)
        self.label_ForRecipe_Change.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_ForRecipe_Change{\n"
"    border-radius: 20px;\n"
"}")
        self.label_ForRecipe_Change.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ForRecipe_Change.setObjectName("label_ForRecipe_Change")
        self.verticalLayout_2.addWidget(self.label_ForRecipe_Change)
        self.label_workAmount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_workAmount.setFont(font)
        self.label_workAmount.setObjectName("label_workAmount")
        self.verticalLayout_2.addWidget(self.label_workAmount)
        self.label_prod_qty = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_prod_qty.setFont(font)
        self.label_prod_qty.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_prod_qty{\n"
"    border-radius: 20px;\n"
"}")
        self.label_prod_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prod_qty.setObjectName("label_prod_qty")
        self.verticalLayout_2.addWidget(self.label_prod_qty)
        self.label_partNumber = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_partNumber.setFont(font)
        self.label_partNumber.setObjectName("label_partNumber")
        self.verticalLayout_2.addWidget(self.label_partNumber)
        self.label_part_no = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_part_no.setFont(font)
        self.label_part_no.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_part_no{\n"
"    border-radius: 20px;\n"
"}")
        self.label_part_no.setAlignment(QtCore.Qt.AlignCenter)
        self.label_part_no.setObjectName("label_part_no")
        self.verticalLayout_2.addWidget(self.label_part_no)
        self.label_partName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_partName.setFont(font)
        self.label_partName.setObjectName("label_partName")
        self.verticalLayout_2.addWidget(self.label_partName)
        self.label_item_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_item_name.setFont(font)
        self.label_item_name.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_item_name{\n"
"    border-radius: 20px;\n"
"}")
        self.label_item_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_item_name.setObjectName("label_item_name")
        self.verticalLayout_2.addWidget(self.label_item_name)
        self.label_workAmountReal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_workAmountReal.setFont(font)
        self.label_workAmountReal.setObjectName("label_workAmountReal")
        self.verticalLayout_2.addWidget(self.label_workAmountReal)
        self.label_detect_amount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_detect_amount.setFont(font)
        self.label_detect_amount.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_detect_amount{\n"
"    border-radius: 20px;\n"
"}")
        self.label_detect_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_detect_amount.setObjectName("label_detect_amount")
        self.verticalLayout_2.addWidget(self.label_detect_amount)
        self.label_passAmount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_passAmount.setFont(font)
        self.label_passAmount.setObjectName("label_passAmount")
        self.verticalLayout_2.addWidget(self.label_passAmount)
        self.label_passdetect_amount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(26)
        self.label_passdetect_amount.setFont(font)
        self.label_passdetect_amount.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_passdetect_amount{\n"
"    border-radius: 20px;\n"
"}")
        self.label_passdetect_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passdetect_amount.setObjectName("label_passdetect_amount")
        self.verticalLayout_2.addWidget(self.label_passdetect_amount)
        self.label_NGAmount = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_NGAmount.setFont(font)
        self.label_NGAmount.setObjectName("label_NGAmount")
        self.verticalLayout_2.addWidget(self.label_NGAmount)
        self.lineEdit_NG_Count = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_NG_Count.sizePolicy().hasHeightForWidth())
        self.lineEdit_NG_Count.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.lineEdit_NG_Count.setFont(font)
        self.lineEdit_NG_Count.setStyleSheet("QLineEdit{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#lineEdit_NG_Count{\n"
"    border-radius: 20px;\n"
"}")
        self.lineEdit_NG_Count.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_NG_Count.setObjectName("lineEdit_NG_Count")
        self.verticalLayout_2.addWidget(self.lineEdit_NG_Count)
        self.comboBox_recipe = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_recipe.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(18)
        self.comboBox_recipe.setFont(font)
        self.comboBox_recipe.setObjectName("comboBox_recipe")
        self.verticalLayout_2.addWidget(self.comboBox_recipe)
        self.pushButton_24Hours = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_24Hours.setFont(font)
        self.pushButton_24Hours.setObjectName("pushButton_24Hours")
        self.verticalLayout_2.addWidget(self.pushButton_24Hours)
        self.pushButton_TakeImage = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_TakeImage.setFont(font)
        self.pushButton_TakeImage.setObjectName("pushButton_TakeImage")
        self.verticalLayout_2.addWidget(self.pushButton_TakeImage)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 2, 1)
        Screwdriver_Detection_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screwdriver_Detection_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        Screwdriver_Detection_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screwdriver_Detection_Window)
        self.statusbar.setObjectName("statusbar")
        Screwdriver_Detection_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Screwdriver_Detection_Window)
        QtCore.QMetaObject.connectSlotsByName(Screwdriver_Detection_Window)

    def retranslateUi(self, Screwdriver_Detection_Window):
        _translate = QtCore.QCoreApplication.translate
        Screwdriver_Detection_Window.setWindowTitle(_translate("Screwdriver_Detection_Window", "Lancer AOI Dectect"))
        self.pushButton_Start.setAccessibleName(_translate("Screwdriver_Detection_Window", "Start"))
        self.pushButton_Start.setText(_translate("Screwdriver_Detection_Window", "檢測"))
        self.pushButton_Reset.setText(_translate("Screwdriver_Detection_Window", "關閉蜂鳴器"))
        self.pushButton_ReDetect.setText(_translate("Screwdriver_Detection_Window", "複檢"))
        self.pushButton_Load_Recipe.setText(_translate("Screwdriver_Detection_Window", "工單掃描"))
        self.pushButton_Recipe_End.setText(_translate("Screwdriver_Detection_Window", "工單結束"))
        self.pushButton_engineer_mode.setText(_translate("Screwdriver_Detection_Window", "工程模式"))
        self.label_workNumber.setText(_translate("Screwdriver_Detection_Window", "工單號碼"))
        self.label_ForRecipe_Change.setText(_translate("Screwdriver_Detection_Window", "工單號碼"))
        self.label_workAmount.setText(_translate("Screwdriver_Detection_Window", "工單數量"))
        self.label_prod_qty.setText(_translate("Screwdriver_Detection_Window", "工單數量"))
        self.label_partNumber.setText(_translate("Screwdriver_Detection_Window", "料號"))
        self.label_part_no.setText(_translate("Screwdriver_Detection_Window", "料號"))
        self.label_partName.setText(_translate("Screwdriver_Detection_Window", "品名"))
        self.label_item_name.setText(_translate("Screwdriver_Detection_Window", "品名"))
        self.label_workAmountReal.setText(_translate("Screwdriver_Detection_Window", "實際檢測數量"))
        self.label_detect_amount.setText(_translate("Screwdriver_Detection_Window", "實際檢測數量"))
        self.label_passAmount.setText(_translate("Screwdriver_Detection_Window", "合格數量"))
        self.label_passdetect_amount.setText(_translate("Screwdriver_Detection_Window", "合格數量"))
        self.label_NGAmount.setText(_translate("Screwdriver_Detection_Window", "NG數(首次)"))
        self.lineEdit_NG_Count.setText(_translate("Screwdriver_Detection_Window", "NG_Count"))
        self.pushButton_24Hours.setText(_translate("Screwdriver_Detection_Window", "24Hours"))
        self.pushButton_TakeImage.setText(_translate("Screwdriver_Detection_Window", "Take image"))
