# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screwdriver_Detection_EngineerMode_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screwdriver_Detection_EngineerMode_Window(object):
    def setupUi(self, Screwdriver_Detection_EngineerMode_Window):
        Screwdriver_Detection_EngineerMode_Window.setObjectName("Screwdriver_Detection_EngineerMode_Window")
        Screwdriver_Detection_EngineerMode_Window.resize(1812, 1091)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Screwdriver_Detection_EngineerMode_Window.sizePolicy().hasHeightForWidth())
        Screwdriver_Detection_EngineerMode_Window.setSizePolicy(sizePolicy)
        Screwdriver_Detection_EngineerMode_Window.setMinimumSize(QtCore.QSize(0, 0))
        Screwdriver_Detection_EngineerMode_Window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Screwdriver_Detection_EngineerMode_Window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Logo/Lancer Small Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Screwdriver_Detection_EngineerMode_Window.setWindowIcon(icon)
        Screwdriver_Detection_EngineerMode_Window.setStyleSheet("background: \'white\';")
        self.centralwidget = QtWidgets.QWidget(Screwdriver_Detection_EngineerMode_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Logo.sizePolicy().hasHeightForWidth())
        self.label_Logo.setSizePolicy(sizePolicy)
        self.label_Logo.setMinimumSize(QtCore.QSize(629, 176))
        self.label_Logo.setMaximumSize(QtCore.QSize(629, 176))
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap("UI_Logo/Lancer Logo_origin_629.png"))
        self.label_Logo.setScaledContents(False)
        self.label_Logo.setObjectName("label_Logo")
        self.verticalLayout.addWidget(self.label_Logo)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(631, 120))
        self.label.setMaximumSize(QtCore.QSize(631, 120))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_TakeImage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TakeImage.sizePolicy().hasHeightForWidth())
        self.pushButton_TakeImage.setSizePolicy(sizePolicy)
        self.pushButton_TakeImage.setMinimumSize(QtCore.QSize(631, 101))
        self.pushButton_TakeImage.setMaximumSize(QtCore.QSize(631, 101))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.pushButton_TakeImage.setFont(font)
        self.pushButton_TakeImage.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Start {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_TakeImage.setObjectName("pushButton_TakeImage")
        self.verticalLayout.addWidget(self.pushButton_TakeImage)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_Motor_Move = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Motor_Move.setMinimumSize(QtCore.QSize(639, 190))
        self.groupBox_Motor_Move.setMaximumSize(QtCore.QSize(641, 191))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.groupBox_Motor_Move.setFont(font)
        self.groupBox_Motor_Move.setObjectName("groupBox_Motor_Move")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Motor_Move)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton_Motor_Out = QtWidgets.QPushButton(self.groupBox_Motor_Move)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Motor_Out.sizePolicy().hasHeightForWidth())
        self.pushButton_Motor_Out.setSizePolicy(sizePolicy)
        self.pushButton_Motor_Out.setMinimumSize(QtCore.QSize(619, 54))
        self.pushButton_Motor_Out.setMaximumSize(QtCore.QSize(621, 54))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.pushButton_Motor_Out.setFont(font)
        self.pushButton_Motor_Out.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Motor_Forward {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Motor_Out.setObjectName("pushButton_Motor_Out")
        self.gridLayout_2.addWidget(self.pushButton_Motor_Out, 0, 0, 1, 1)
        self.pushButton_Motor_In = QtWidgets.QPushButton(self.groupBox_Motor_Move)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Motor_In.sizePolicy().hasHeightForWidth())
        self.pushButton_Motor_In.setSizePolicy(sizePolicy)
        self.pushButton_Motor_In.setMinimumSize(QtCore.QSize(619, 54))
        self.pushButton_Motor_In.setMaximumSize(QtCore.QSize(621, 54))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.pushButton_Motor_In.setFont(font)
        self.pushButton_Motor_In.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Motor_Backward {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Motor_In.setObjectName("pushButton_Motor_In")
        self.gridLayout_2.addWidget(self.pushButton_Motor_In, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Motor_Move)
        spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.groupBox_AI_Light = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_AI_Light.setMinimumSize(QtCore.QSize(631, 118))
        self.groupBox_AI_Light.setMaximumSize(QtCore.QSize(641, 121))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.groupBox_AI_Light.setFont(font)
        self.groupBox_AI_Light.setObjectName("groupBox_AI_Light")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_AI_Light)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_AI_Light_On = QtWidgets.QCheckBox(self.groupBox_AI_Light)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_AI_Light_On.sizePolicy().hasHeightForWidth())
        self.checkBox_AI_Light_On.setSizePolicy(sizePolicy)
        self.checkBox_AI_Light_On.setMaximumSize(QtCore.QSize(202, 59))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.checkBox_AI_Light_On.setFont(font)
        self.checkBox_AI_Light_On.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_AI_Light_On.setAutoExclusive(True)
        self.checkBox_AI_Light_On.setObjectName("checkBox_AI_Light_On")
        self.gridLayout_4.addWidget(self.checkBox_AI_Light_On, 0, 0, 1, 1)
        self.checkBox_AOI_Light_On = QtWidgets.QCheckBox(self.groupBox_AI_Light)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_AOI_Light_On.sizePolicy().hasHeightForWidth())
        self.checkBox_AOI_Light_On.setSizePolicy(sizePolicy)
        self.checkBox_AOI_Light_On.setMaximumSize(QtCore.QSize(203, 59))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.checkBox_AOI_Light_On.setFont(font)
        self.checkBox_AOI_Light_On.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_AOI_Light_On.setAutoExclusive(True)
        self.checkBox_AOI_Light_On.setObjectName("checkBox_AOI_Light_On")
        self.gridLayout_4.addWidget(self.checkBox_AOI_Light_On, 0, 1, 1, 1)
        self.checkBox_AI_Light_Off = QtWidgets.QCheckBox(self.groupBox_AI_Light)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_AI_Light_Off.sizePolicy().hasHeightForWidth())
        self.checkBox_AI_Light_Off.setSizePolicy(sizePolicy)
        self.checkBox_AI_Light_Off.setMaximumSize(QtCore.QSize(202, 59))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.checkBox_AI_Light_Off.setFont(font)
        self.checkBox_AI_Light_Off.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_AI_Light_Off.setAutoFillBackground(False)
        self.checkBox_AI_Light_Off.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_AI_Light_Off.setAutoExclusive(True)
        self.checkBox_AI_Light_Off.setObjectName("checkBox_AI_Light_Off")
        self.gridLayout_4.addWidget(self.checkBox_AI_Light_Off, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_AI_Light)
        spacerItem4 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.groupBox_Buzzer = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Buzzer.setMinimumSize(QtCore.QSize(631, 118))
        self.groupBox_Buzzer.setMaximumSize(QtCore.QSize(641, 118))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.groupBox_Buzzer.setFont(font)
        self.groupBox_Buzzer.setObjectName("groupBox_Buzzer")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_Buzzer)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_buzzerOn = QtWidgets.QCheckBox(self.groupBox_Buzzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_buzzerOn.sizePolicy().hasHeightForWidth())
        self.checkBox_buzzerOn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.checkBox_buzzerOn.setFont(font)
        self.checkBox_buzzerOn.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_buzzerOn.setAutoExclusive(True)
        self.checkBox_buzzerOn.setObjectName("checkBox_buzzerOn")
        self.horizontalLayout.addWidget(self.checkBox_buzzerOn)
        self.checkBox_buzzerOff = QtWidgets.QCheckBox(self.groupBox_Buzzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_buzzerOff.sizePolicy().hasHeightForWidth())
        self.checkBox_buzzerOff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.checkBox_buzzerOff.setFont(font)
        self.checkBox_buzzerOff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_buzzerOff.setAutoFillBackground(False)
        self.checkBox_buzzerOff.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_buzzerOff.setChecked(True)
        self.checkBox_buzzerOff.setAutoExclusive(True)
        self.checkBox_buzzerOff.setObjectName("checkBox_buzzerOff")
        self.horizontalLayout.addWidget(self.checkBox_buzzerOff)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Buzzer)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image.sizePolicy().hasHeightForWidth())
        self.label_Image.setSizePolicy(sizePolicy)
        self.label_Image.setMinimumSize(QtCore.QSize(500, 919))
        self.label_Image.setStyleSheet("box-shadow: 0px 0px 16px 20px rgba(0,0,0,1);")
        self.label_Image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout_2.addWidget(self.label_Image)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_OK = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_OK.sizePolicy().hasHeightForWidth())
        self.label_OK.setSizePolicy(sizePolicy)
        self.label_OK.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(72)
        self.label_OK.setFont(font)
        self.label_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.label_OK.setText("")
        self.label_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OK.setObjectName("label_OK")
        self.verticalLayout_2.addWidget(self.label_OK)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_recipe_combobox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_recipe_combobox.sizePolicy().hasHeightForWidth())
        self.groupBox_recipe_combobox.setSizePolicy(sizePolicy)
        self.groupBox_recipe_combobox.setMinimumSize(QtCore.QSize(627, 150))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.groupBox_recipe_combobox.setFont(font)
        self.groupBox_recipe_combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_recipe_combobox.setObjectName("groupBox_recipe_combobox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_recipe_combobox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_recipe = QtWidgets.QComboBox(self.groupBox_recipe_combobox)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.comboBox_recipe.setFont(font)
        self.comboBox_recipe.setObjectName("comboBox_recipe")
        self.gridLayout_10.addWidget(self.comboBox_recipe, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_recipe_combobox)
        self.groupBox_language = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_language.sizePolicy().hasHeightForWidth())
        self.groupBox_language.setSizePolicy(sizePolicy)
        self.groupBox_language.setMinimumSize(QtCore.QSize(627, 150))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.groupBox_language.setFont(font)
        self.groupBox_language.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_language.setObjectName("groupBox_language")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_language)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_language_tv = QtWidgets.QCheckBox(self.groupBox_language)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_language_tv.sizePolicy().hasHeightForWidth())
        self.checkBox_language_tv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.checkBox_language_tv.setFont(font)
        self.checkBox_language_tv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_language_tv.setAutoFillBackground(False)
        self.checkBox_language_tv.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_language_tv.setAutoExclusive(True)
        self.checkBox_language_tv.setObjectName("checkBox_language_tv")
        self.gridLayout.addWidget(self.checkBox_language_tv, 0, 3, 1, 1)
        self.checkBox_language_zh = QtWidgets.QCheckBox(self.groupBox_language)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_language_zh.sizePolicy().hasHeightForWidth())
        self.checkBox_language_zh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.checkBox_language_zh.setFont(font)
        self.checkBox_language_zh.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_language_zh.setAutoExclusive(True)
        self.checkBox_language_zh.setObjectName("checkBox_language_zh")
        self.gridLayout.addWidget(self.checkBox_language_zh, 0, 0, 1, 1)
        self.checkBox_language_en = QtWidgets.QCheckBox(self.groupBox_language)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_language_en.sizePolicy().hasHeightForWidth())
        self.checkBox_language_en.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.checkBox_language_en.setFont(font)
        self.checkBox_language_en.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_language_en.setAutoExclusive(True)
        self.checkBox_language_en.setObjectName("checkBox_language_en")
        self.gridLayout.addWidget(self.checkBox_language_en, 0, 1, 1, 1)
        self.checkBox_language_pt = QtWidgets.QCheckBox(self.groupBox_language)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_language_pt.sizePolicy().hasHeightForWidth())
        self.checkBox_language_pt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.checkBox_language_pt.setFont(font)
        self.checkBox_language_pt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_language_pt.setAutoFillBackground(False)
        self.checkBox_language_pt.setStyleSheet("QCheckBox{\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"QCheckBox:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QCheckBox:checked{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}")
        self.checkBox_language_pt.setAutoExclusive(True)
        self.checkBox_language_pt.setObjectName("checkBox_language_pt")
        self.gridLayout.addWidget(self.checkBox_language_pt, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_language)
        spacerItem6 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem6)
        self.pushButton_24Hours = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24Hours.sizePolicy().hasHeightForWidth())
        self.pushButton_24Hours.setSizePolicy(sizePolicy)
        self.pushButton_24Hours.setMinimumSize(QtCore.QSize(627, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.pushButton_24Hours.setFont(font)
        self.pushButton_24Hours.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_24Hours {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_24Hours.setObjectName("pushButton_24Hours")
        self.verticalLayout_3.addWidget(self.pushButton_24Hours)
        spacerItem7 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem7)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(627, 199))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_TakeImage_File_Route = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TakeImage_File_Route.sizePolicy().hasHeightForWidth())
        self.label_TakeImage_File_Route.setSizePolicy(sizePolicy)
        self.label_TakeImage_File_Route.setMinimumSize(QtCore.QSize(607, 52))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label_TakeImage_File_Route.setFont(font)
        self.label_TakeImage_File_Route.setStyleSheet("QLabel{\n"
"    background-color: #eef0ef;\n"
"    border: 1px solid #dcdfe6;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    color : #595758;\n"
"}\n"
"\n"
"#label_part_no{\n"
"    border-radius: 20px;\n"
"}")
        self.label_TakeImage_File_Route.setObjectName("label_TakeImage_File_Route")
        self.verticalLayout_4.addWidget(self.label_TakeImage_File_Route)
        self.pushButton_Change_TakeImage_File_Route = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Change_TakeImage_File_Route.sizePolicy().hasHeightForWidth())
        self.pushButton_Change_TakeImage_File_Route.setSizePolicy(sizePolicy)
        self.pushButton_Change_TakeImage_File_Route.setMinimumSize(QtCore.QSize(607, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.pushButton_Change_TakeImage_File_Route.setFont(font)
        self.pushButton_Change_TakeImage_File_Route.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Start {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Change_TakeImage_File_Route.setObjectName("pushButton_Change_TakeImage_File_Route")
        self.verticalLayout_4.addWidget(self.pushButton_Change_TakeImage_File_Route)
        self.pushButton_Open_TakeImage_File_Route = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Open_TakeImage_File_Route.sizePolicy().hasHeightForWidth())
        self.pushButton_Open_TakeImage_File_Route.setSizePolicy(sizePolicy)
        self.pushButton_Open_TakeImage_File_Route.setMinimumSize(QtCore.QSize(607, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.pushButton_Open_TakeImage_File_Route.setFont(font)
        self.pushButton_Open_TakeImage_File_Route.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_Start {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_Open_TakeImage_File_Route.setObjectName("pushButton_Open_TakeImage_File_Route")
        self.verticalLayout_4.addWidget(self.pushButton_Open_TakeImage_File_Route)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem8 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem8)
        self.pushButton_open_dbWindow = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open_dbWindow.sizePolicy().hasHeightForWidth())
        self.pushButton_open_dbWindow.setSizePolicy(sizePolicy)
        self.pushButton_open_dbWindow.setMinimumSize(QtCore.QSize(627, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.pushButton_open_dbWindow.setFont(font)
        self.pushButton_open_dbWindow.setStyleSheet("QPushButton {\n"
"    background-color: #e8ecef;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95949a;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked {\n"
"    border: 1px solid #e8ecef;\n"
"}\n"
"\n"
"#pushButton_24Hours {\n"
"    border-radius: 20px;\n"
"}")
        self.pushButton_open_dbWindow.setObjectName("pushButton_open_dbWindow")
        self.verticalLayout_3.addWidget(self.pushButton_open_dbWindow)
        spacerItem9 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem9)
        self.groupBox_plcState = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plcState.sizePolicy().hasHeightForWidth())
        self.groupBox_plcState.setSizePolicy(sizePolicy)
        self.groupBox_plcState.setMinimumSize(QtCore.QSize(627, 120))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.groupBox_plcState.setFont(font)
        self.groupBox_plcState.setObjectName("groupBox_plcState")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_plcState)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_plc_m0 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m0.setFont(font)
        self.label_plc_m0.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m0.setObjectName("label_plc_m0")
        self.gridLayout_3.addWidget(self.label_plc_m0, 0, 0, 1, 1)
        self.label_plc_m1 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m1.setFont(font)
        self.label_plc_m1.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m1.setObjectName("label_plc_m1")
        self.gridLayout_3.addWidget(self.label_plc_m1, 0, 1, 1, 1)
        self.label_plc_m2 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m2.setFont(font)
        self.label_plc_m2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m2.setObjectName("label_plc_m2")
        self.gridLayout_3.addWidget(self.label_plc_m2, 0, 2, 1, 1)
        self.label_plc_m3 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m3.setFont(font)
        self.label_plc_m3.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m3.setObjectName("label_plc_m3")
        self.gridLayout_3.addWidget(self.label_plc_m3, 0, 3, 1, 1)
        self.label_plc_m6 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m6.setFont(font)
        self.label_plc_m6.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m6.setObjectName("label_plc_m6")
        self.gridLayout_3.addWidget(self.label_plc_m6, 0, 4, 1, 1)
        self.label_plc_m20 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m20.setFont(font)
        self.label_plc_m20.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m20.setObjectName("label_plc_m20")
        self.gridLayout_3.addWidget(self.label_plc_m20, 1, 0, 1, 1)
        self.label_plc_m21 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m21.setFont(font)
        self.label_plc_m21.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m21.setObjectName("label_plc_m21")
        self.gridLayout_3.addWidget(self.label_plc_m21, 1, 1, 1, 1)
        self.label_plc_m22 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m22.setFont(font)
        self.label_plc_m22.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m22.setObjectName("label_plc_m22")
        self.gridLayout_3.addWidget(self.label_plc_m22, 1, 2, 1, 1)
        self.label_plc_m23 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m23.setFont(font)
        self.label_plc_m23.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m23.setObjectName("label_plc_m23")
        self.gridLayout_3.addWidget(self.label_plc_m23, 1, 3, 1, 1)
        self.label_plc_m28 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m28.setFont(font)
        self.label_plc_m28.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m28.setObjectName("label_plc_m28")
        self.gridLayout_3.addWidget(self.label_plc_m28, 1, 4, 1, 1)
        self.label_plc_m24 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m24.setFont(font)
        self.label_plc_m24.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m24.setObjectName("label_plc_m24")
        self.gridLayout_3.addWidget(self.label_plc_m24, 2, 0, 1, 1)
        self.label_plc_m25 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m25.setFont(font)
        self.label_plc_m25.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m25.setObjectName("label_plc_m25")
        self.gridLayout_3.addWidget(self.label_plc_m25, 2, 1, 1, 1)
        self.label_plc_m26 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m26.setFont(font)
        self.label_plc_m26.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m26.setObjectName("label_plc_m26")
        self.gridLayout_3.addWidget(self.label_plc_m26, 2, 2, 1, 1)
        self.label_plc_m27 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m27.setFont(font)
        self.label_plc_m27.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m27.setObjectName("label_plc_m27")
        self.gridLayout_3.addWidget(self.label_plc_m27, 2, 3, 1, 1)
        self.label_plc_m29 = QtWidgets.QLabel(self.groupBox_plcState)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_plc_m29.setFont(font)
        self.label_plc_m29.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_plc_m29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_plc_m29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plc_m29.setObjectName("label_plc_m29")
        self.gridLayout_3.addWidget(self.label_plc_m29, 2, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_plcState)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        Screwdriver_Detection_EngineerMode_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screwdriver_Detection_EngineerMode_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1812, 21))
        self.menubar.setObjectName("menubar")
        Screwdriver_Detection_EngineerMode_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screwdriver_Detection_EngineerMode_Window)
        self.statusbar.setObjectName("statusbar")
        Screwdriver_Detection_EngineerMode_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Screwdriver_Detection_EngineerMode_Window)
        QtCore.QMetaObject.connectSlotsByName(Screwdriver_Detection_EngineerMode_Window)

    def retranslateUi(self, Screwdriver_Detection_EngineerMode_Window):
        _translate = QtCore.QCoreApplication.translate
        Screwdriver_Detection_EngineerMode_Window.setWindowTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "Lancer AOI Dectect"))
        self.label.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "     工程模式"))
        self.pushButton_TakeImage.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "取像"))
        self.groupBox_Motor_Move.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "平台移動"))
        self.pushButton_Motor_Out.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "出"))
        self.pushButton_Motor_In.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "進"))
        self.groupBox_AI_Light.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "檢測光源"))
        self.checkBox_AI_Light_On.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "AI燈光 ON"))
        self.checkBox_AOI_Light_On.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "AOI燈光 ON"))
        self.checkBox_AI_Light_Off.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "OFF"))
        self.groupBox_Buzzer.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "蜂鳴器"))
        self.checkBox_buzzerOn.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "ON"))
        self.checkBox_buzzerOff.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "OFF"))
        self.groupBox_recipe_combobox.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "工單選擇"))
        self.groupBox_language.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "語系選擇"))
        self.checkBox_language_tv.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "Tiếng Việt"))
        self.checkBox_language_zh.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "中文"))
        self.checkBox_language_en.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "English"))
        self.checkBox_language_pt.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "ภาษาไทย"))
        self.pushButton_24Hours.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "24小時檢測"))
        self.groupBox.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "取像檔案路徑"))
        self.label_TakeImage_File_Route.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "File Route(不能有中文路徑)"))
        self.pushButton_Change_TakeImage_File_Route.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "設定取像檔案路徑"))
        self.pushButton_Open_TakeImage_File_Route.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "開啟取像檔案路徑"))
        self.pushButton_open_dbWindow.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "開啟資料庫"))
        self.groupBox_plcState.setTitle(_translate("Screwdriver_Detection_EngineerMode_Window", "PLC狀態"))
        self.label_plc_m0.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "M0"))
        self.label_plc_m1.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "M1"))
        self.label_plc_m2.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "M2"))
        self.label_plc_m3.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "M3"))
        self.label_plc_m6.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "M6"))
        self.label_plc_m20.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "G(M20)"))
        self.label_plc_m21.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "Y(M21)"))
        self.label_plc_m22.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "R(M22)"))
        self.label_plc_m23.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "A(M23)"))
        self.label_plc_m28.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "LimitOut(M28)"))
        self.label_plc_m24.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "L1(M24)"))
        self.label_plc_m25.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "L2(M25)"))
        self.label_plc_m26.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "L3(M26)"))
        self.label_plc_m27.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "L4(M27)"))
        self.label_plc_m29.setText(_translate("Screwdriver_Detection_EngineerMode_Window", "LimitIn(M29)"))
